en:
  label: English
  weight: 1
  contentDir: content/en
  title: "SAGE : Self, Altruism, Groups, & Empathy"
  params:
    lab_name: "SAGE"
    lab_full_name: "SAGE : Self, Altruism, Groups, & Empathy"
    institution: "Université du Québec à Rimouski (UQAR)"
fr:
  label: Français
  weight: 2
  contentDir: content/fr
  title: "SAGE : Soi, Altruisme, Groupes, et Empathie"
  params:
    lab_name: "SAGE"
    lab_full_name: "SAGE : Soi, Altruisme, Groupes, et Empathie"
    institution: "Université du Québec à Rimouski (UQAR)"
