main:
  - name: Recherche
    url: recherche/
    weight: 20
  - name: Projets
    url: projets/
    weight: 25
  - name: Équipe
    url: equipe/
    weight: 30
  - name: Publications
    url: publications/
    weight: 40
  - name: Joindre l'équipe
    url: nous-joindre/
    weight: 60
  - name: Contact
    url: contact/
    weight: 70
